### ISSUE TITLE
Miscalculated zr？

### ISSUE THREAD

**Issue by hugen79** [ttrftech/NanoVNA#2]
Is there an error in line 574 of plot.c
`float zr = ((1+coeff[0])*(1-coeff[0]) + coeff[1]*coeff[1]) * d;`

I think the right is
`float zr = ((1+coeff[0])*(1-coeff[0]) - coeff[1]*coeff[1]) * d;`

**Comment by edy555** [comment]
You're right!
I fixed by commit af17abd0538c6db47c9035b2923a2b7ec675f6b6
