### ISSUE TITLE
No more than 3 Memories usable

### ISSUE THREAD

**Issue by df6dbf** [ttrftech/NanoVNA#36]
I have installed your last Firmware,
hat trouble to save more than 3 Memories. At the 4th the cal procedure is fine but if i want to recall the Memory it contains Garbage.

Have Reset the Calibration Data before and try to erase the config. 

Its not important on witch place i store the memory.

73s Holger, DF6DBF

**Comment by edy555** [comment]
Unfortunately, cannot reproduce the failure.
Could you let me the detail of the procedure?

**Comment by df6dbf** [comment]
I think my problems caused that i have a Power Supply via USB connected. The next try this evening with the internal Battery was succesful. :)

73 Holger, DF6DBF
