### ISSUE TITLE
Use complex conjugate in FFT for TDR

### ISSUE THREAD

**Issue by erikkaashoek** [ttrftech/NanoVNA#41]
For TDR , instead of doing a window function its better to extend the  FFT to
twice the length with the complex conjugate and use a 256 point FFT

**Comment by erikkaashoek** [comment]
Furthermore, can you switch the display of trace 0 to "Linear" and refpos=4 and scale =0.04
This will show both above Z0 and below Z0 impedance steps

**Comment by edy555** [comment]
Thanks for the suggestion. fixed by #42
Put off changing format automatically at this time.
