### ISSUE TITLE
calibration reset at attempt to change stimulus

### ISSUE THREAD

**Issue by qrp73** [ttrftech/NanoVNA#53]
STR:
1) calibrate device: open,short,load,isoln,thru
2) make sure calibration is ok
3) open menu stimulus and change stop frequency
4) make sure calibration is unexpectedly reset

This bug appears after latest commits (scan command, etc)

**Comment by edy555** [comment]
Just fixed at https://github.com/ttrftech/NanoVNA/commit/0d3662141100992b1afefc9d2448207c26d953ba
Thanks!

**Comment by qrp73** [comment]
Confirmed. Now it works as expected. 
Thanks
