### ISSUE TITLE
Add new command: TDR disable through console (Enhancement)

### ISSUE THREAD

**Issue by nlroth** [ttrftech/NanoVNA#62]
Is it possible to add a new console command so that the NanoVNA-Saver app can turn off TDR if it is enabled?

**Comment by edy555** [comment]
Just added transform command at https://github.com/ttrftech/NanoVNA/commit/50bce6457589d3ae358954cb0f30ac3c9a0eca55
please check it out!

**Comment by nlroth** [comment]
Thanks!Will check it out. 

 
 
  On Fri, 4 Oct 2019 at 9:15 PM, TT<notifications@github.com> wrote:   
Just added transform command at 50bce64
please check it out!

**Comment by nlroth** [comment]
Sorry, I have been busy and forgot to confirm via email - I checked it out the day you released and it works as intended.
Thank you.

    On Friday, October 11, 2019, 8:47:32 a.m. GMT-4, TT <notifications@github.com> wrote:  
 
 
Closed #62.
