### ISSUE TITLE
Make it possible to set NEGATIVE edelay

### ISSUE THREAD

**Issue by erikkaashoek** [ttrftech/NanoVNA#74]
After calibration you may use the device without the female-female adaptor or without the cables and you may want to have a negative edelay.
This implements the change

@@ -1211,6 +1211,7 @@ const keypads_t keypads_time[] = {
  { KP_X(2), KP_Y(0), 9 },
  { KP_X(3), KP_Y(2), KP_N },
  { KP_X(3), KP_Y(3), KP_P },
+  { KP_X(3), KP_Y(1), KP_MINUS },
  { KP_X(2), KP_Y(3), KP_BS },
  { 0, 0, -1 }
};

@@ -1712,6 +1713,9 @@ keypad_click(int key)
    return KP_DONE;
  } else if (c <= 9 && kp_index < NUMINPUT_LEN)
    kp_buf[kp_index++] = '0' + c;
+  else if (c == KP_MINUS && kp_index < NUMINPUT_LEN) {
+    kp_buf[kp_index++] = '-';
+  }
  else if (c == KP_PERIOD && kp_index < NUMINPUT_LEN) {
    // check period in former input
    int j;

**Comment by edy555** [comment]
Oh just added last night in this commit
https://github.com/ttrftech/NanoVNA/commit/0e982aa834cd542ae40a3a066d87590d33a80000
Will become available in the next release.
