### ISSUE TITLE
New firmware 0.4.0 doens't work as expected...

### ISSUE THREAD

**Issue by dl9sec** [ttrftech/NanoVNA#96]
Hi,

got my NanoVNA two days ago with a well working, but unknown version firmware:

![NanoVNA_OldFW](https://user-images.githubusercontent.com/7019835/68392944-2e694200-016b-11ea-969f-d8613d7778c5.jpg)

I backed up 128kB of the flash with dfu-util and tried the latest v0.4.0. The firmware runs, but the measurement seems to be broken:

![NanoVNA_FW040](https://user-images.githubusercontent.com/7019835/68393004-53f64b80-016b-11ea-9b2e-c6f7e2b39fbd.jpg)

A calibration doesn't change anything.
If i restore the firmware with my backup, all runs well again, measurements are plausible.
So i assume, the hardware itself works.

Did i miss something to make the measurement work? Some kind of factory resetting or so?
Any ideas?

Thanks in advance,

Thorsten

**Edit:**
As far as i see, the delivered firmware seems to be the "Antenna Analyzer" variant (maybe from hugen79?). I built hugens AA firmware from sources and it works very well, but both "normal" builds, that of ttrftech and hugen79 showing the same behaviour...

**Comment by edy555** [comment]
Could you try command `clearconfig 1234` after flashing?

**Comment by insanumingenium** [comment]
I had the same exact scenario, was banging my head against garbage starting around 300Mhz regardless of calibration.  Below that it was working normally, and nanovnasaver seemed to give better results (didn't test extensively).

Clearing worked for me, now seems to be working 100%.

**Comment by dl9sec** [comment]
Confirm. Tnx :-D
