### ISSUE TITLE
Smith value format is not persistent

### ISSUE THREAD

**Issue by owenduffy** [ttrftech/NanoVNA#99]
It appears that selecting Smith value format R+jX does not persist over power off.

The text also collides with the entry to the right.

![Screenshot-191211061717](https://user-images.githubusercontent.com/4297310/70561087-f166f400-1bdd-11ea-8c19-9ce5121e4795.png)

**Comment by edy555** [comment]
Yes, currently smith value format is not stored but will be supported in near releases.

**Comment by owenduffy** [comment]
It could be argued that the default format should be R+jX.

Further, that your Ω symbol should be on the right hand end of the value, there should be no space between real and imaginary parts (with a + sign to separate as needed), and the J should be j (J is for joules) and be between the imaginary parts sign and its numeric characters.

Screen space is very valuable, so why not abbreviate SMITH to SM? If there is no facility to scale the Smith chart display, what is the value of the "1.0FS" display?

Adding this feature is a significant improvement on the hammy presentation, fixing these issues is as big an improvement.

Thanks for the good work.

Owen

**Comment by jp3141** [comment]
so the format should look like:
`49.2-j2.87m Ω` // only space is between the last character of the value and the Ω symbol

**Comment by owenduffy** [comment]
Quite, but screen space is a premium so I have no problems with no space between value and unit (as is done with other quantities).

**Comment by edy555** [comment]
Smith value format became persistent in 0.6.0 release https://github.com/ttrftech/NanoVNA/releases/tag/0.6.0
